# Bayesian Socio-Geodemographic SSE Regression

It uses the reusable library modules to prepare model frames, formulas, output paths, Bambi fits, posterior summaries, diagnostics, and saved result tables.

The notebook is arranged by model family and domain:

- Logistic regression: `candidate` as the outcome.
- Linear regression: `burst_score` and `burden_score` as outcomes.
- Mixing models: node-level entropy/context predictors.
- Composition models: sequence-level socio-geodemographic predictors.

In [1]:
from __future__ import annotations

from pathlib import Path
import os
import sys

os.environ.setdefault("JAX_PLATFORMS", "cpu")

import pandas as pd

PROJECT_ROOT = Path.cwd().resolve()
while not (PROJECT_ROOT / "utils").exists() and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
if not (PROJECT_ROOT / "utils").exists():
    raise RuntimeError("Run this notebook from inside the scotland repository.")

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sse_detection.lib import (  # noqa: E402
    BayesianFitConfig,
    SampleSpec,
    fit_prepared_model,
    load_sse_outputs,
    prepare_regression_data,
    prepare_regression_run,
    save_prepared_model_result,
)

SSE_OUTPUT_DIR = PROJECT_ROOT / "sse_detection" / "results" / "sse_outputs"
RESULT_DIR = (
    PROJECT_ROOT / "sse_detection" / "results" / "bayesian_socio_geo_demo_regression"
)
LOGISTIC_RESULT_DIR = RESULT_DIR / "logistic"
LINEAR_RESULT_DIR = RESULT_DIR / "linear"

## Load and Align Data

Nodes at least as large as the smallest high-priority burst/burden candidate. Sequence-level composition rows inherit the candidate label and score outcomes from their cluster.

In [2]:
sse_outputs = load_sse_outputs(SSE_OUTPUT_DIR)
regression_data = prepare_regression_data(sse_outputs)

print(f"Minimum candidate cluster size: {regression_data.min_candidate_size}")
display(regression_data.eligibility_summary)

Minimum candidate cluster size: 6

,dataset,rows,candidate_rate,candidates,burst_score_nonmissing,burden_score_nonmissing
0,eligible_nodes,13059,0.047017,614,13059,921
1,eligible_sequence_data,264139,0.253049,66840,264139,23308

## Sampling and Fit Configuration

The notebook uses a small fraction of data for every complete-case frame. Logistic samples preserve the observed candidate fraction by default; composition samples also seed categorical levels so treatment-coded terms stay valid.

Increase `rows`, `fraction`, `draws`, or `tune` when moving from smoke-test to final analysis.

In [3]:
RANDOM_SEED = 123
DISPLAY_TABLES = True
SAVE_INFERENCE_DATA = False

FIT_CONFIG = BayesianFitConfig(
    draws=2000,
    tune=2000,
    chains=4,
    cores=4,
    target_accept=0.99,
    random_seed=RANDOM_SEED,
    inference_method="pymc",
)

mixing_rate = float(regression_data.eligible_nodes["candidate"].mean())
composition_rate = float(regression_data.eligible_sequence_data["candidate"].mean())

MIXING_SAMPLE = SampleSpec(
    fraction=1.0,
    positive_fraction=mixing_rate,
    random_state=RANDOM_SEED,
)
COMPOSITION_SAMPLE = SampleSpec(
    fraction=1.0,
    positive_fraction=composition_rate,
    random_state=RANDOM_SEED,
)

print(f"Mixing candidate rate: {mixing_rate:.3%}")
print(f"Composition candidate rate: {composition_rate:.3%}")

Mixing candidate rate: 4.702%
Composition candidate rate: 25.305%

## Build Model Frames and Formula Grids

This creates complete-case frames, sampled fit frames, Bambi formulas, and organized output directories for all available configurations.

In [4]:
logistic_run = prepare_regression_run(
    regression_data,
    family="logistic",
    result_dir=LOGISTIC_RESULT_DIR,
    mixing_sample=MIXING_SAMPLE,
    composition_sample=COMPOSITION_SAMPLE,
    write_tables=True,
)

linear_run = prepare_regression_run(
    regression_data,
    family="linear",
    result_dir=LINEAR_RESULT_DIR,
    mixing_sample=MIXING_SAMPLE,
    composition_sample=COMPOSITION_SAMPLE,
    write_tables=True,
)

print("Logistic model grid")
display(logistic_run.model_grid)
print("Logistic fit-frame summary")
display(logistic_run.fit_frame_summary)

print("Linear model grid")
display(linear_run.model_grid)
print("Linear fit-frame summary")
display(linear_run.fit_frame_summary)

Logistic model grid

,family,domain,outcome,model_set,predictor,formula,model_dir
0,logistic,mixing,candidate,null_primary,null_predictors,candidate ~ sex_entropy_z + age_entropy_z + si...,/home/s1879429/Desktop/PhD Project/scotland/ss...
1,logistic,mixing,candidate,null_expanded,null_predictors_plus_context,candidate ~ sex_entropy_z + age_entropy_z + si...,/home/s1879429/Desktop/PhD Project/scotland/ss...
2,logistic,mixing,candidate,observed_primary,observed_predictors,candidate ~ sex_entropy_obs_x10 + age_entropy_...,/home/s1879429/Desktop/PhD Project/scotland/ss...
3,logistic,mixing,candidate,observed_expanded,observed_predictors_plus_context,candidate ~ sex_entropy_obs_x10 + age_entropy_...,/home/s1879429/Desktop/PhD Project/scotland/ss...
4,logistic,composition,candidate,primary,composition_predictors,"candidate ~ C(sex, Treatment(reference='Male')...",/home/s1879429/Desktop/PhD Project/scotland/ss...
5,logistic,composition,candidate,expanded,composition_predictors_plus_context,"candidate ~ C(sex, Treatment(reference='Male')...",/home/s1879429/Desktop/PhD Project/scotland/ss...

Logistic fit-frame summary

,frame,family,domain,outcome,model_set,model_dir,full_rows,fit_rows,fit_fraction,use_sample,full_candidates,fit_candidates,full_candidate_rate,fit_candidate_rate
0,null_primary,logistic,mixing,candidate,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,12967,1.0,False,614,614,0.047351,0.047351
1,null_expanded,logistic,mixing,candidate,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,12967,1.0,False,614,614,0.047351,0.047351
2,observed_primary,logistic,mixing,candidate,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,13059,1.0,False,614,614,0.047017,0.047017
3,observed_expanded,logistic,mixing,candidate,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,13059,1.0,False,614,614,0.047017,0.047017
4,primary,logistic,composition,candidate,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,264139,264139,1.0,False,66840,66840,0.253049,0.253049
5,expanded,logistic,composition,candidate,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,264127,264127,1.0,False,66840,66840,0.253060,0.253060

Linear model grid

,family,domain,outcome,model_set,predictor,formula,model_dir
0,linear,mixing,burst_score,null_primary,null_predictors,burst_score ~ sex_entropy_z + age_entropy_z + ...,/home/s1879429/Desktop/PhD Project/scotland/ss...
1,linear,mixing,burst_score,null_expanded,null_predictors_plus_context,burst_score ~ sex_entropy_z + age_entropy_z + ...,/home/s1879429/Desktop/PhD Project/scotland/ss...
2,linear,mixing,burst_score,observed_primary,observed_predictors,burst_score ~ sex_entropy_obs_x10 + age_entrop...,/home/s1879429/Desktop/PhD Project/scotland/ss...
3,linear,mixing,burst_score,observed_expanded,observed_predictors_plus_context,burst_score ~ sex_entropy_obs_x10 + age_entrop...,/home/s1879429/Desktop/PhD Project/scotland/ss...
4,linear,mixing,burden_score,null_primary,null_predictors,burden_score ~ sex_entropy_z + age_entropy_z +...,/home/s1879429/Desktop/PhD Project/scotland/ss...
5,linear,mixing,burden_score,null_expanded,null_predictors_plus_context,burden_score ~ sex_entropy_z + age_entropy_z +...,/home/s1879429/Desktop/PhD Project/scotland/ss...
6,linear,mixing,burden_score,observed_primary,observed_predictors,burden_score ~ sex_entropy_obs_x10 + age_entro...,/home/s1879429/Desktop/PhD Project/scotland/ss...
7,linear,mixing,burden_score,observed_expanded,observed_predictors_plus_context,burden_score ~ sex_entropy_obs_x10 + age_entro...,/home/s1879429/Desktop/PhD Project/scotland/ss...
8,linear,composition,burst_score,primary,composition_predictors,"burst_score ~ C(sex, Treatment(reference='Male...",/home/s1879429/Desktop/PhD Project/scotland/ss...
9,linear,composition,burst_score,expanded,composition_predictors_plus_context,"burst_score ~ C(sex, Treatment(reference='Male...",/home/s1879429/Desktop/PhD Project/scotland/ss...
10,linear,composition,burden_score,primary,composition_predictors,"burden_score ~ C(sex, Treatment(reference='Mal...",/home/s1879429/Desktop/PhD Project/scotland/ss...
11,linear,composition,burden_score,expanded,composition_predictors_plus_context,"burden_score ~ C(sex, Treatment(reference='Mal...",/home/s1879429/Desktop/PhD Project/scotland/ss...

Linear fit-frame summary

,frame,family,domain,outcome,model_set,model_dir,full_rows,fit_rows,fit_fraction,use_sample,full_outcome_mean,fit_outcome_mean,full_outcome_sd,fit_outcome_sd
0,burst_score_null_primary,linear,mixing,burst_score,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,12967,1.0,False,0.503235,0.503235,0.238025,0.238025
1,burst_score_null_expanded,linear,mixing,burst_score,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,12967,1.0,False,0.503235,0.503235,0.238025,0.238025
2,burst_score_observed_primary,linear,mixing,burst_score,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,13059,1.0,False,0.502565,0.502565,0.237816,0.237816
3,burst_score_observed_expanded,linear,mixing,burst_score,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,13059,1.0,False,0.502565,0.502565,0.237816,0.237816
4,burden_score_null_primary,linear,mixing,burden_score,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,921,1.0,False,0.530945,0.530945,0.258088,0.258088
5,burden_score_null_expanded,linear,mixing,burden_score,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,921,1.0,False,0.530945,0.530945,0.258088,0.258088
6,burden_score_observed_primary,linear,mixing,burden_score,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,921,1.0,False,0.530945,0.530945,0.258088,0.258088
7,burden_score_observed_expanded,linear,mixing,burden_score,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,921,1.0,False,0.530945,0.530945,0.258088,0.258088
8,burst_score_primary,linear,composition,burst_score,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,264139,264139,1.0,False,0.720155,0.720155,0.231404,0.231404
9,burst_score_expanded,linear,composition,burst_score,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,264127,264127,1.0,False,0.720152,0.720152,0.231404,0.231404
10,burden_score_primary,linear,composition,burden_score,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,23308,23308,1.0,False,0.425268,0.425268,0.258110,0.258110
11,burden_score_expanded,linear,composition,burden_score,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,23303,23303,1.0,False,0.425145,0.425145,0.258001,0.258001

## Shared Fitting Helper

Each model cell below calls this helper. It fits one prepared frame, prints diagnostics/posterior summaries, and writes `summary.csv`, `diagnostics.csv`, and `metadata.csv` under the frame's configured output directory.

In [5]:
FIT_RESULTS = {}
MANIFEST_ROWS = []


def fit_and_save_frame(prepared, *, domain: str, outcome: str, model_set: str):
    """Fit one prepared model frame and save the standard output files."""
    frame = prepared.select(domain=domain, outcome=outcome, model_set=model_set)
    key = f"{frame.family}:{domain}:{outcome}:{model_set}"
    print("=" * 100)
    print(key)
    print(frame.formula)
    print(
        f"Fit rows: {len(frame.fit_df):,} / complete-case rows: {len(frame.full_df):,}"
    )
    print(f"Output dir: {frame.output_dir.relative_to(PROJECT_ROOT)}")

    result = fit_prepared_model(
        frame,
        config=FIT_CONFIG,
        display_tables=DISPLAY_TABLES,
        print_diagnostics=True,
    )
    manifest_row = save_prepared_model_result(
        result,
        frame,
        save_idata=SAVE_INFERENCE_DATA,
    )
    FIT_RESULTS[key] = result
    MANIFEST_ROWS.append(manifest_row)
    return result

# Logistic Candidate Models

Outcome: `candidate`.

The primary models include the focal composition or mixing predictors. Expanded models add epidemic/surveillance context adjusters.

## Logistic Mixing: Null Primary

Node-level candidate association with null-standardised mixing features.

In [6]:
logistic_mixing_null_primary = fit_and_save_frame(
    logistic_run,
    domain="mixing",
    outcome="candidate",
    model_set="null_primary",
)

====================================================================================================
logistic:mixing:candidate:null_primary
candidate ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + (1|policy_period) + (1|clade)
Fit rows: 12,967 / complete-case rows: 12,967
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/mixing/null_primary

Modeling the probability that candidate==1
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 122 seconds.
There was 1 divergence after tuning. Increase `target_accept` or reparameterize.

Skipping unavailable posterior variables:
  - sigma

Bayesian model diagnostics
==========================

Posterior summary
=================

Skipping unavailable posterior variables:
  - sigma

## Logistic Mixing: Null Expanded

Node-level candidate association with null-standardised mixing features plus context adjusters.

In [7]:
logistic_mixing_null_expanded = fit_and_save_frame(
    logistic_run,
    domain="mixing",
    outcome="candidate",
    model_set="null_expanded",
)

====================================================================================================
logistic:mixing:candidate:null_expanded
candidate ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 12,967 / complete-case rows: 12,967
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/mixing/null_expanded

Modeling the probability that candidate==1
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 153 seconds.

Skipping unavailable posterior variables:
  - sigma

Bayesian model diagnostics
==========================

Posterior summary
=================

Skipping unavailable posterior variables:
  - sigma

## Logistic Mixing: Observed Primary

Node-level candidate association with observed entropy scales.

In [8]:
logistic_mixing_observed_primary = fit_and_save_frame(
    logistic_run,
    domain="mixing",
    outcome="candidate",
    model_set="observed_primary",
)

Modeling the probability that candidate==1

====================================================================================================
logistic:mixing:candidate:observed_primary
candidate ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + (1|policy_period) + (1|clade)
Fit rows: 13,059 / complete-case rows: 13,059
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/mixing/observed_primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 182 seconds.

Skipping unavailable posterior variables:
  - sigma

Bayesian model diagnostics
==========================

Posterior summary
=================

Skipping unavailable posterior variables:
  - sigma

## Logistic Mixing: Observed Expanded

Node-level candidate association with observed entropy scales plus context adjusters.

In [9]:
logistic_mixing_observed_expanded = fit_and_save_frame(
    logistic_run,
    domain="mixing",
    outcome="candidate",
    model_set="observed_expanded",
)

Modeling the probability that candidate==1

====================================================================================================
logistic:mixing:candidate:observed_expanded
candidate ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 13,059 / complete-case rows: 13,059
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/mixing/observed_expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 184 seconds.

Skipping unavailable posterior variables:
  - sigma

Bayesian model diagnostics
==========================

Posterior summary
=================

Skipping unavailable posterior variables:
  - sigma

## Logistic Composition: Primary

Sequence-level candidate association with sex, age band, SIMD quintile, urban/rural class, and health board.

In [6]:
logistic_composition_primary = fit_and_save_frame(
    logistic_run,
    domain="composition",
    outcome="candidate",
    model_set="primary",
)

====================================================================================================
logistic:composition:candidate:primary
candidate ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + (1|policy_period) + (1|clade)
Fit rows: 264,139 / complete-case rows: 264,139
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/composition/primary

Modeling the probability that candidate==1
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 277322 seconds.
Chain 0 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 1 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 2 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
Chain 3 reached the maximum tree depth. Increase `max_treedepth`, increase `target_accept` or reparameterize.
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details

:

## Logistic Composition: Expanded

Sequence-level candidate association with composition predictors plus context adjusters.

In [ ]:
logistic_composition_expanded = fit_and_save_frame(
    logistic_run,
    domain="composition",
    outcome="candidate",
    model_set="expanded",
)

Modeling the probability that candidate==1

====================================================================================================
logistic:composition:candidate:expanded
candidate ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 26,413 / complete-case rows: 264,127
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/logistic/composition/expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 80413 seconds.

Skipping unavailable posterior variables:
  - sigma

Bayesian model diagnostics
==========================

Posterior summary
=================

Skipping unavailable posterior variables:
  - sigma

# Linear Score Models

Outcomes: `burst_score` and `burden_score`.

These use the same mixing/composition predictor sets as the logistic candidate models, but report coefficient direction probabilities rather than odds ratios.

## Linear Mixing: Burst Score / Null Primary

In [12]:
linear_mixing_burst_null_primary = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burst_score",
    model_set="null_primary",
)

====================================================================================================
linear:mixing:burst_score:null_primary
burst_score ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + (1|policy_period) + (1|clade)
Fit rows: 12,967 / complete-case rows: 12,967
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burst_score/null_primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 94 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burst Score / Null Expanded

In [13]:
linear_mixing_burst_null_expanded = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burst_score",
    model_set="null_expanded",
)

====================================================================================================
linear:mixing:burst_score:null_expanded
burst_score ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 12,967 / complete-case rows: 12,967
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burst_score/null_expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)
/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 85 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burst Score / Observed Primary

In [14]:
linear_mixing_burst_observed_primary = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burst_score",
    model_set="observed_primary",
)

====================================================================================================
linear:mixing:burst_score:observed_primary
burst_score ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + (1|policy_period) + (1|clade)
Fit rows: 13,059 / complete-case rows: 13,059
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burst_score/observed_primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 175 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burst Score / Observed Expanded

In [15]:
linear_mixing_burst_observed_expanded = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burst_score",
    model_set="observed_expanded",
)

====================================================================================================
linear:mixing:burst_score:observed_expanded
burst_score ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 13,059 / complete-case rows: 13,059
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burst_score/observed_expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)
/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 194 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burden Score / Null Primary

In [16]:
linear_mixing_burden_null_primary = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burden_score",
    model_set="null_primary",
)

====================================================================================================
linear:mixing:burden_score:null_primary
burden_score ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + (1|policy_period) + (1|clade)
Fit rows: 921 / complete-case rows: 921
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burden_score/null_primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 17 seconds.
There were 2 divergences after tuning. Increase `target_accept` or reparameterize.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burden Score / Null Expanded

In [17]:
linear_mixing_burden_null_expanded = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burden_score",
    model_set="null_expanded",
)

====================================================================================================
linear:mixing:burden_score:null_expanded
burden_score ~ sex_entropy_z + age_entropy_z + simd_entropy_z + urban_rural_entropy_z + health_board_entropy_z + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 921 / complete-case rows: 921
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burden_score/null_expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_z, age_entropy_z, simd_entropy_z, urban_rural_entropy_z, health_board_entropy_z, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 18 seconds.
There were 4 divergences after tuning. Increase `target_accept` or reparameterize.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burden Score / Observed Primary

In [18]:
linear_mixing_burden_observed_primary = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burden_score",
    model_set="observed_primary",
)

====================================================================================================
linear:mixing:burden_score:observed_primary
burden_score ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + (1|policy_period) + (1|clade)
Fit rows: 921 / complete-case rows: 921
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burden_score/observed_primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 13 seconds.
There was 1 divergence after tuning. Increase `target_accept` or reparameterize.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Mixing: Burden Score / Observed Expanded

In [19]:
linear_mixing_burden_observed_expanded = fit_and_save_frame(
    linear_run,
    domain="mixing",
    outcome="burden_score",
    model_set="observed_expanded",
)

====================================================================================================
linear:mixing:burden_score:observed_expanded
burden_score ~ sex_entropy_obs_x10 + age_entropy_obs_x10 + simd_entropy_obs_x10 + urban_rural_entropy_obs_x10 + health_board_entropy_obs_x10 + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 921 / complete-case rows: 921
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/mixing/burden_score/observed_expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, sex_entropy_obs_x10, age_entropy_obs_x10, simd_entropy_obs_x10, urban_rural_entropy_obs_x10, health_board_entropy_obs_x10, wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 14 seconds.
There was 1 divergence after tuning. Increase `target_accept` or reparameterize.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Composition: Burst Score / Primary

In [ ]:
linear_composition_burst_primary = fit_and_save_frame(
    linear_run,
    domain="composition",
    outcome="burst_score",
    model_set="primary",
)

====================================================================================================
linear:composition:burst_score:primary
burst_score ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + (1|policy_period) + (1|clade)
Fit rows: 26,414 / complete-case rows: 264,139
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/composition/burst_score/primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 86225 seconds.
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Composition: Burst Score / Expanded

In [ ]:
linear_composition_burst_expanded = fit_and_save_frame(
    linear_run,
    domain="composition",
    outcome="burst_score",
    model_set="expanded",
)

====================================================================================================
linear:composition:burst_score:expanded
burst_score ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 26,413 / complete-case rows: 264,127
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/composition/burst_score/expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 87080 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Composition: Burden Score / Primary

In [ ]:
linear_composition_burden_primary = fit_and_save_frame(
    linear_run,
    domain="composition",
    outcome="burden_score",
    model_set="primary",
)

====================================================================================================
linear:composition:burden_score:primary
burden_score ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + (1|policy_period) + (1|clade)
Fit rows: 2,331 / complete-case rows: 23,308
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/composition/burden_score/primary

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

/home/s1879429/anaconda3/envs/PhD/lib/python3.13/site-packages/pymc/step_methods/hmc/quadpotential.py:321: RuntimeWarning: overflow encountered in dot
  return 0.5 * np.dot(x, v_out)

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 51 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

## Linear Composition: Burden Score / Expanded

In [ ]:
linear_composition_burden_expanded = fit_and_save_frame(
    linear_run,
    domain="composition",
    outcome="burden_score",
    model_set="expanded",
)

====================================================================================================
linear:composition:burden_score:expanded
burden_score ~ C(sex, Treatment(reference='Male')) + C(age_band, Treatment(reference='20-24')) + C(dz_simd_quintile, Treatment(reference=1)) + C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')) + C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')) + wn_prop_sequenced_z + dz_cum_incidence_per_capita_z + dz_cum_prop_sequenced_z + (1|policy_period) + (1|clade)
Fit rows: 2,330 / complete-case rows: 23,303
Output dir: sse_detection/results/bayesian_socio_geo_demo_regression/linear/composition/burden_score/expanded

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, C(sex, Treatment(reference='Male')), C(age_band, Treatment(reference='20-24')), C(dz_simd_quintile, Treatment(reference=1)), C(dz_urban_rural_class, Treatment(reference='Large Urban Areas')), C(dz_health_board, Treatment(reference='Greater Glasgow and Clyde')), wn_prop_sequenced_z, dz_cum_incidence_per_capita_z, dz_cum_prop_sequenced_z, 1|policy_period_sigma, 1|policy_period_offset, 1|clade_sigma, 1|clade_offset]

Output()

Sampling 4 chains for 2_000 tune and 2_000 draw iterations (8_000 + 8_000 draws total) took 65 seconds.

Bayesian model diagnostics
==========================

Posterior summary
=================

# Saved Model Manifest

This collects the rows written by each fitting cell. Re-run this after fitting any subset of models.

In [24]:
saved_model_manifest = pd.DataFrame(MANIFEST_ROWS)
if not saved_model_manifest.empty:
    combined_manifest_path = RESULT_DIR / "saved_model_manifest.csv"
    saved_model_manifest.to_csv(combined_manifest_path, index=False)
    print(
        f"Saved combined manifest to: {combined_manifest_path.relative_to(PROJECT_ROOT)}"
    )
display(saved_model_manifest)

Saved combined manifest to: sse_detection/results/bayesian_socio_geo_demo_regression/saved_model_manifest.csv

,family,domain,outcome,model_set,model_dir,n_rows,candidate_rate,outcome_mean,outcome_sd,use_sample
0,logistic,mixing,candidate,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,0.047351,0.047351,NaN,False
1,logistic,mixing,candidate,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,0.047351,0.047351,NaN,False
2,logistic,mixing,candidate,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,0.047017,0.047017,NaN,False
3,logistic,mixing,candidate,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,0.047017,0.047017,NaN,False
4,logistic,composition,candidate,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,26414,0.253048,0.253048,NaN,True
5,logistic,composition,candidate,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,26413,0.253057,0.253057,NaN,True
6,linear,mixing,burst_score,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,NaN,0.503235,0.238025,False
7,linear,mixing,burst_score,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,12967,NaN,0.503235,0.238025,False
8,linear,mixing,burst_score,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,NaN,0.502565,0.237816,False
9,linear,mixing,burst_score,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,13059,NaN,0.502565,0.237816,False
10,linear,mixing,burden_score,null_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,NaN,0.530945,0.258088,False
11,linear,mixing,burden_score,null_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,NaN,0.530945,0.258088,False
12,linear,mixing,burden_score,observed_primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,NaN,0.530945,0.258088,False
13,linear,mixing,burden_score,observed_expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,921,NaN,0.530945,0.258088,False
14,linear,composition,burst_score,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,26414,NaN,0.721990,0.230691,True
15,linear,composition,burst_score,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,26413,NaN,0.720442,0.231709,True
16,linear,composition,burden_score,primary,/home/s1879429/Desktop/PhD Project/scotland/ss...,2331,NaN,0.413216,0.250317,True
17,linear,composition,burden_score,expanded,/home/s1879429/Desktop/PhD Project/scotland/ss...,2330,NaN,0.416818,0.252952,True